# models/__init__.py
from sqlmodel import SQLModel

from .chat import Chat, ChatBase, ChatOut, ChatsOut, ChatUpdate
from .document import (
    Document,
    DocumentBase,
    DocumentCreate,
    DocumentKind,
    DocumentOut,
    DocumentsOut,
    DocumentUpdate,
)
from .item import Item, ItemBase, ItemCreate, ItemOut, ItemsOut, ItemUpdate
from .mcp_server import (
    MCPServer,
    MCPServerBase,
    MCPServerCreate,
    MCPServerKind,
    MCPServerOut,
    MCPServerOutWithTemplate,
    MCPServersOut,
    MCPServersOutWithTemplate,
    MCPServerStatus,
    MCPServerUpdate,
)
from .message import Message, MessageCreate, MessageOut, MessagesOut
from .project import (
    Project,
    ProjectBase,
    ProjectCreate,
    ProjectOut,
    ProjectsOut,
    ProjectUpdate,
)
from .secret import (
    Secret,
    SecretBase,
    SecretCreate,
    SecretOut,
    SecretSearch,
    SecretsOut,
    SecretUpdate,
    SecretWithValueOut,
)
from .suggestion import (
    Suggestion,
    SuggestionBase,
    SuggestionCreate,
    SuggestionOut,
    SuggestionsOut,
    SuggestionUpdate,
)
from .team import (
    Team,
    TeamCreate,
    TeamInvitationStatus,
    TeamMember,
    TeamMemberCreate,
    TeamMemberOut,
    TeamMembersOut,
    TeamMemberUpdate,
    TeamOut,
    TeamOutWithMembers,
    TeamRole,
    TeamsOut,
    TeamUpdate,
)

# Import base models first
from .user import (
    UpdatePassword,
    User,
    UserBase,
    UserCreate,
    UserOut,
    UserRegister,
    UsersOut,
    UserUpdate,
    UserUpdateMe,
)
from .utils import NewPassword, Token, TokenPayload, UtilsMessage
from .vote import Vote, VoteBase, VoteCreate, VoteOut, VotesOut, VoteUpdate

__all__ = [
    "Item",
    "Project",
    "ProjectBase",
    "ProjectCreate",
    "ProjectOut",
    "ProjectsOut",
    "ProjectUpdate",
    "Team",
    "TeamMember",
    "TeamCreate",
    "TeamOut",
    "TeamsOut",
    "TeamInvitationStatus",
    "TeamRole",
    "TeamUpdate",
    "TeamMemberCreate",
    "TeamMemberUpdate",
    "TeamMemberOut",
    "TeamMembersOut",
    "TeamOutWithMembers",
    "User",
    "UserBase",
    "UserCreate",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UpdatePassword",
    "UserOut",
    "UsersOut",
    "Item",
    "ItemBase",
    "ItemCreate",
    "ItemUpdate",
    "ItemOut",
    "ItemsOut",
    "UtilsMessage",
    "Token",
    "TokenPayload",
    "NewPassword",
    "Chat",
    "ChatBase",
    "ChatUpdate",
    "ChatOut",
    "ChatsOut",
    "SQLModel",
    "Message",
    "MessageCreate",
    "MessageOut",
    "MessagesOut",
    "Vote",
    "VoteBase",
    "VoteCreate",
    "VoteUpdate",
    "VoteOut",
    "VotesOut",
    "Document",
    "DocumentBase",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentKind",
    "DocumentOut",
    "DocumentsOut",
    "Suggestion",
    "SuggestionBase",
    "SuggestionCreate",
    "SuggestionUpdate",
    "SuggestionOut",
    "SuggestionsOut",
    "AuthType",
    "AuthConfig",
    "TokenAuth",
    "ApiKeyAuth",
    "BasicAuth",
    "MCPServer",
    "MCPServerBase",
    "MCPServerCreate",
    "MCPServerUpdate",
    "MCPServerOut",
    "MCPServersOut",
    "MCPServerStatus",
    "MCPServerKind",
    "MCPServerOutWithTemplate",
    "MCPServersOutWithTemplate",
    "Secret",
    "SecretBase",
    "SecretCreate",
    "SecretUpdate",
    "SecretOut",
    "SecretsOut",
    "SecretSearch",
    "SecretWithValueOut",
]
