# models/__init__.py
from sqlmodel import SQLModel

from .chat import Chat, ChatBase, ChatOut, ChatsOut, ChatUpdate
from .connection import (
    ApiKeyAuth,
    AuthConfig,
    AuthType,
    BasicAuth,
    Connection,
    ConnectionBase,
    ConnectionCreate,
    ConnectionOut,
    ConnectionSearch,
    ConnectionsOut,
    ConnectionUpdate,
    TokenAuth,
)
from .document import (
    Document,
    DocumentBase,
    DocumentCreate,
    DocumentKind,
    DocumentOut,
    DocumentsOut,
    DocumentUpdate,
)
from .item import Item, ItemBase, ItemCreate, ItemOut, ItemsOut, ItemUpdate
from .mcp_instance import (
    MCPInstance,
    MCPInstanceBase,
    MCPInstanceCreate,
    MCPInstanceOut,
    MCPInstanceSearch,
    MCPInstancesOut,
    MCPInstanceStatus,
    MCPInstanceUpdate,
)
from .message import Message, MessageCreate, MessageOut, MessagesOut
from .project import (
    Project,
    ProjectBase,
    ProjectCreate,
    ProjectOut,
    ProjectsOut,
    ProjectUpdate,
)
from .suggestion import (
    Suggestion,
    SuggestionBase,
    SuggestionCreate,
    SuggestionOut,
    SuggestionsOut,
    SuggestionUpdate,
)
from .team import (
    Team,
    TeamCreate,
    TeamInvitationStatus,
    TeamMember,
    TeamMemberCreate,
    TeamMemberOut,
    TeamMembersOut,
    TeamMemberUpdate,
    TeamOut,
    TeamOutWithMembers,
    TeamRole,
    TeamsOut,
    TeamUpdate,
)
from .tool_instance import (
    ToolInstance,
    ToolInstanceBase,
    ToolInstanceCreate,
    ToolInstanceOut,
    ToolInstanceSearch,
    ToolInstancesOut,
    ToolInstanceStatus,
    ToolInstanceUpdate,
)

# Import base models first
from .user import (
    UpdatePassword,
    User,
    UserBase,
    UserCreate,
    UserOut,
    UserRegister,
    UsersOut,
    UserUpdate,
    UserUpdateMe,
)
from .utils import NewPassword, Token, TokenPayload, UtilsMessage
from .vote import Vote, VoteBase, VoteCreate, VoteOut, VotesOut, VoteUpdate

__all__ = [
    "Item",
    "Project",
    "ProjectBase",
    "ProjectCreate",
    "ProjectOut",
    "ProjectsOut",
    "ProjectUpdate",
    "Team",
    "TeamMember",
    "TeamCreate",
    "TeamOut",
    "TeamsOut",
    "TeamInvitationStatus",
    "TeamRole",
    "TeamUpdate",
    "TeamMemberCreate",
    "TeamMemberUpdate",
    "TeamMemberOut",
    "TeamMembersOut",
    "TeamOutWithMembers",
    "User",
    "UserBase",
    "UserCreate",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UpdatePassword",
    "UserOut",
    "UsersOut",
    "Item",
    "ItemBase",
    "ItemCreate",
    "ItemUpdate",
    "ItemOut",
    "ItemsOut",
    "UtilsMessage",
    "Token",
    "TokenPayload",
    "NewPassword",
    "Chat",
    "ChatBase",
    "ChatUpdate",
    "ChatOut",
    "ChatsOut",
    "SQLModel",
    "Message",
    "MessageCreate",
    "MessageOut",
    "MessagesOut",
    "Vote",
    "VoteBase",
    "VoteCreate",
    "VoteUpdate",
    "VoteOut",
    "VotesOut",
    "Document",
    "DocumentBase",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentKind",
    "DocumentOut",
    "DocumentsOut",
    "Suggestion",
    "SuggestionBase",
    "SuggestionCreate",
    "SuggestionUpdate",
    "SuggestionOut",
    "SuggestionsOut",
    "Connection",
    "ConnectionBase",
    "ConnectionCreate",
    "ConnectionUpdate",
    "ConnectionOut",
    "ConnectionsOut",
    "ConnectionSearch",
    "AuthType",
    "AuthConfig",
    "TokenAuth",
    "ApiKeyAuth",
    "BasicAuth",
    "ToolInstance",
    "ToolInstanceBase",
    "ToolInstanceCreate",
    "ToolInstanceUpdate",
    "ToolInstanceOut",
    "ToolInstancesOut",
    "ToolInstanceStatus",
    "ToolInstanceSearch",
    "MCPInstance",
    "MCPInstanceBase",
    "MCPInstanceCreate",
    "MCPInstanceUpdate",
    "MCPInstanceOut",
    "MCPInstancesOut",
    "MCPInstanceStatus",
    "MCPInstanceSearch",
]
