name: Feedback
description: Provide feedback or report an issue for Centroid
title: '[Feedback]: '
labels: ['feedback']
body:
  - type: dropdown
    id: feedback-type
    attributes:
      label: Type of Feedback
      description: Please check one of the following
      options:
        - Bug Report
        - Feature Request
        - General Feedback
        - Question
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of your feedback
      placeholder: Tell us what's on your mind...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: If reporting a bug, what did you expect to happen?
      placeholder: I expected that...

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: If reporting a bug, what actually happened?
      placeholder: Instead, what happened was...

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: If reporting a bug, how can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: Chrome, Safari, Firefox, etc.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the browser are you using?
      placeholder: '22'

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about your feedback here
      placeholder: Any other details you'd like to share...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow Centroid's Code of Conduct
          required: true
