"""adding streams table and is_agent fields

Revision ID: 0509509655f3
Revises: d0b3286c7bc5
Create Date: 2025-06-16 20:14:25.278437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0509509655f3'
down_revision = 'd0b3286c7bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streams',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mcp_servers', sa.Column('is_agent', sa.Boolean(), nullable=False))
    op.add_column('mcp_servers', sa.Column('instructions', sa.String(), nullable=True))
    op.add_column('mcp_templates', sa.Column('is_agent', sa.Boolean(), nullable=False))
    op.add_column('mcp_templates', sa.Column('instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_templates', 'instructions')
    op.drop_column('mcp_templates', 'is_agent')
    op.drop_column('mcp_servers', 'instructions')
    op.drop_column('mcp_servers', 'is_agent')
    op.drop_table('streams')
    # ### end Alembic commands ###
