"""rename secrets kind to provider

Revision ID: d3f6184613ab
Revises: b2007c54f1a2
Create Date: 2025-06-19 10:30:14.409084

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd3f6184613ab'
down_revision = 'b2007c54f1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'kind', new_column_name='provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'provider', new_column_name='kind')
    # ### end Alembic commands ###
