"""add is_agent and instructions to mcp_servers

Revision ID: fdde384bdced
Revises: d0b3286c7bc5
Create Date: 2025-06-08 16:32:12.576315

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fdde384bdced'
down_revision = 'd0b3286c7bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('is_agent', sa.Boolean(), nullable=False))
    op.add_column('mcp_servers', sa.Column('instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'instructions')
    op.drop_column('mcp_servers', 'is_agent')
    # ### end Alembic commands ###
